-- Rode este script no SQL Editor do Supabase (projeto > SQL Editor > New query)

create table if not exists public.leads (
    id bigint generated by default as identity primary key,
    created_at timestamptz not null default now(),
    date text,
    type text,
    name text,
    email text,
    phone text,
    income text,
    invested text,
    extra text
);

alter table public.leads enable row level security;

-- Qualquer visitante do formulário pode inserir um lead (submissão pública)
create policy "Public insert leads"
on public.leads
for insert
to anon
with check (true);

-- O painel admin (mesma anon key, protegido só pela senha no front-end) pode ler
create policy "Public select leads"
on public.leads
for select
to anon
using (true);

-- E também apagar (botões "Excluir" / "Limpar Tudo" do painel)
create policy "Public delete leads"
on public.leads
for delete
to anon
using (true);

-- Registra cada abertura do link, mesmo sem preencher o formulário
create table if not exists public.page_views (
    id bigint generated by default as identity primary key,
    created_at timestamptz not null default now(),
    source text
);

alter table public.page_views enable row level security;

-- Qualquer visitante da página pode gerar um registro de visualização
create policy "Public insert page_views"
on public.page_views
for insert
to anon
with check (true);

-- O painel admin (mesma anon key) pode ler o total de visualizações
create policy "Public select page_views"
on public.page_views
for select
to anon
using (true);
